### ISSUE TITLE
Timeplot for spatial positions of the molecular sites

### ISSUE THREAD

**Issue by vcellmike** [MolClustPy/SpringSaLaD-Python-Viz#5]
Process viewer_files. For each time point, find center of mass for each color node (=site). Start with z only. 

Generate the plot of the distance from center of mass to the membrane over time for each site type. 

For verification, Nephrin is membrane-bound, so its sites are originally all close to the membrane, and stay so. However, Nck and NWASP will eventually be closer to the membrane, and binding sites will be closer than non-binding. 

FUTURE - WILL BE SEPARATE ISSUES: 
1. Weighted center of mass accounting for radius of each site
2. Same for molecules (average of all sites).
3. Add x and y dimensions
4. Same for centers of molecular clusters (connected components).
5. Compute the radius for each molecular cluster.

**Comment by Hlpred** [comment]
Made Average_z_pos.ipynb to find and plot the average z position of a specified site over time. The only issue is I couldn't find a way to figure out the site name just from the viewer file data (some colors correspond to multiple sites in some simulations). For now, you must manually put the site names into a list to see a legend.

This example is for R_L_test_difficult, but it still demonstrates the expected behavior.

![image](https://github.com/MolClustPy/SpringSaLaD-Python-Viz/assets/71465959/33ce8d48-1e0a-44b8-ae43-501f6087bf8f)

**Comment by vcellmike** [comment]
*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***
Hi Harrison,

To find color-site matching you need to process input file. Just have two files open.

Best,
Michael
________________________________

**Comment by Hlpred** [comment]
I just made it so the legend is automatically generated from the input file

**Comment by vcellmike** [comment]
*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***
Hi Harrison,

Thank you for the updates! I checked all the files and with little adjustments, all of them work on Mac for Nephrin-Nick-Nwasp system that I will discuss tomorrow. Please don't make any changes till my talk.

I forgot, are you coming to the center tomorrow or connecting by WebEx? Although it's always more convenient to meet in person, it's OK to connect remotely. After the seminar, I'll be available till 2:30pm, and then I'll be busy for about an hour, so it may be not worth driving 2 hours for 2 hours of communication. But you need to connect online and test that you can hear and talk - I'll introduce you to the audience.

Generally, the code works nicely but needs a lot of usability and commonality improvements, e.g. paths should be treated the same in all files. We'll discuss it after the seminar.

Best,
Michael


________________________________

**Comment by Hlpred** [comment]
Yes, I'm already here in person for the talk later today.
